name: 编译/测试

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: 编译/测试
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 初始化pnpm环境
        uses: pnpm/action-setup@v2

      - name: 安装依赖
        run: pnpm i

      - name: esLint 检查
        run: pnpm run lint

      - name: typescript 检查
        run: pnpm run typecheck

      - name: 执行测试
        run: pnpm run test

      - name: 编译
        run: pnpm run build
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
