name: 发布

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: 发布
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 初始化pnpm环境
        uses: pnpm/action-setup@v2

      - name: 安装依赖
        run: pnpm i

      - name: esLint 检查
        run: pnpm lint

      - name: typescript 检查
        run: pnpm typecheck

      - name: 执行测试
        run: pnpm test

      - name: 创建 github release, 生成 release describe
        id: release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node

      - name: 编译 & 发布
        run: pnpm build
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
