name: 发布

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: 发布
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        node-version: [14]
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 初始化 node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: 安装依赖
        run: npm install

      - name: esLint 检查
        run: npm run lint

      - name: typescript 检查
        run: npm run typecheck

      - name: 执行测试
        run: npm run test

      - name: 创建 github release, 生成 release 内容
        run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: 编译 & 发布
        run: npm run build
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
