name: 发布

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: 发布
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [windows-latest]
        node-version: [14]
        pnpm-version: [7]
    env:
      ELECTRON_CACHE: ${{ github.workspace }}/.cache/electron
      ELECTRON_BUILDER_CACHE: ${{ github.workspace }}/.cache/electron-builder
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 初始化 pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm-version }}
          run_install: false

      - name: 初始化 node, 缓存 pnpm
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: 缓存 Electron
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.cache/electron
          key: ${{ runner.os }}-electron-cache-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: |
            ${{ runner.os }}-electron-cache-

      - name: 缓存 Electron-Builder
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.cache/electron-builder
          key: ${{ runner.os }}-electron-builder-cache-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: |
            ${{ runner.os }}-electron-builder-cache-

      - name: 安装 ni
        run: npm i -g @antfu/ni

      - name: 安装依赖
        run: nci

      - name: esLint 检查
        run: nr lint

      - name: typescript 检查
        run: nr typecheck

      - name: 执行测试
        run: nr test

      - name: 创建 github release, 生成 release 内容
        run: nx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: 编译 & 发布
        run: nr build
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
