name: 测试

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: 测试
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        node-version: [14]
        pnpm-version: [7]
    env:
      ELECTRON_CACHE: ${{ github.workspace }}/.cache/electron
      ELECTRON_BUILDER_CACHE: ${{ github.workspace }}/.cache/electron-builder
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 初始化pnpm环境
        uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm-version }}

      - name: 初始化 node, 缓存 pnpm
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: 缓存 Electron
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.cache/electron
          key: ${{ runner.os }}-electron-cache-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-electron-cache-

      - name: 缓存 Electron-Builder
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.cache/electron-builder
          key: ${{ runner.os }}-electron-builder-cache-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-electron-builder-cache-

      - name: 安装依赖
        run: pnpm install --frozen-lockfile

      - name: esLint 检查
        run: pnpm run lint

      - name: typescript 检查
        run: pnpm run typecheck

      - name: 执行测试
        run: pnpm run test

      - name: 编译
        run: pnpm run build -p never

      - name: 上传构件
        uses: actions/upload-artifact@v3
        with:
          name: electron-build-${{ runner.os }}-node${{ matrix.node-version }}
          path: |
            release
            !release/*-unpacked
          retention-days: 30
