name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: 测试
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        node-version: [14]
        pnpm-version: [7]
    env:
      ELECTRON_CACHE: ${{ github.workspace }}/.cache/electron
      ELECTRON_BUILDER_CACHE: ${{ github.workspace }}/.cache/electron-builder
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 初始化 node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: 安装依赖
        run: npm install

      - name: esLint 检查
        run: npm run lint

      - name: typescript 检查
        run: npm run typecheck

      - name: 执行测试
        run: npm run test

      - name: 编译
        run: npm run build -- -p never

      - name: 上传构件
        uses: actions/upload-artifact@v3
        with:
          name: electron-build-${{ runner.os }}-node${{ matrix.node-version }}
          path: |
            release
            !release/*-unpacked
          retention-days: 30
